export const INITIALIZE_CLIENT = 'INITALIZE_CLIENT';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CLOSE_ALL_MENUS = 'CLOSE_ALL_MENUS';
export const TRANSITION_STATE = 'TRANSITION_STATE';
export const ADD_CONSOLE_MESSAGE = 'ADD_CONSOLE_MESSAGE';
export const EXECUTE_CODE = 'EXECUTE_CODE';
export const TERMINATE_CODE = 'TERMINATE_CODE';
